= The Pragmatic Programmer Quick Reference Guide

This page summarizes the tips and checklists found in _The Pragmatic
Programmer_.

*Care About Your Craft*

Why spend your life developing software unless you care about doing it
well?

*Think! About Your Work*

Turn off the autopilot and take control. Constantly critique and
appraise your work.

*Provide Options, Don&#39;t Make Lame Excuses*

Instead of excuses, provide options. Don&#39;t say it can&#39;t be done;
explain what can be done.

*Don&#39;t Live with Broken Windows*

Fix bad designs, wrong decisions, and poor code when you see them.

*Be a Catalyst for Change*

You can&#39;t force change on people. Instead, show them how the future
might be and help them participate in creating it.

*Remember the Big Picture*

Don&#39;t get so engrossed in the details that you forget to check what&#39;s
happening around you.

*Make Quality a Requirements Issue*

Involve your users in determining the project&#39;s real quality
requirements.

*Invest Regularly in Your Knowledge Portfolio* Make learning a habit.

*Critically Analyze What You Read and Hear*

Don&#39;t be swayed by vendors, media hype, or dogma. Analyze information
in terms of you and your project.

*It&#39;s Both What You Say and the Way You Say It*

There&#39;s no point in having great ideas if you don&#39;t communicate them
effectively.

*DRY–Don&#39;t Repeat Yourself*

Every piece of knowledge must have a single, unambiguous, authoritative
representation within a system.

*Make It Easy to Reuse*

If it&#39;s easy to reuse, people will. Create an environment that supports
reuse.

*Eliminate Effects Between Unrelated Things*

Design components that are self-contained. independent, and have a
single, well-defined purpose.

*There Are No Final Decisions*

No decision is cast in stone. Instead, consider each as being written in
the sand at the beach, and plan for change.

*Use Tracer Bullets to Find the Target*

Tracer bullets let you home in on your target by trying things and
seeing how close they land.

*Prototype to Learn*

Prototyping is a learning experience. Its value lies not in the code you
produce, but in the lessons you learn.

*Program Close to the Problem Domain* Design and code in your user&#39;s
language.

*Estimate to Avoid Surprises*

Estimate before you start. You&#39;ll spot potential problems up front.

*Iterate the Schedule with the Code*

Use experience you gain as you implement to refine the project time
scales.

*Keep Knowledge in Plain Text*

Plain text won&#39;t become obsolete. It helps leverage your work and
simplifies debugging and testing.

*Use the Power of Command Shells*

Use the shell when graphical user interfaces don&#39;t cut it.

*Use a Single Editor Well*

The editor should be an extension of your hand; make sure your editor is
configurable, extensible, and programmable.

*Always Use Source Code Control*

Source code control is a time machine for your work—you can go back.

*Fix the Problem, Not the Blame*

It doesn&#39;t really matter whether the bug is your fault or someone
else&#39;s—it is still your problem, and it still needs to be fixed.

*Don&#39;t Panic When Debugging*

Take a deep breath and THINK! about what could be causing the bug.

*&quot;select&quot; Isn&#39;t Broken.*

It is rare to find a bug in the OS or the compiler, or even a
third-party product or library. The bug is most likely in the
application.

*Don&#39;t Assume It—Prove It*

Prove your assumptions in the actual environment-- with real data and
boundary conditions.

*Learn a Text Manipulation Language.*

You spend a large part of each day working with text. Why not have the
computer do some of it for you?

*Write Code That Writes Code*

Code generators increase your productivity and help avoid duplication.

*You Can&#39;t Write Perfect Software*

Software can&#39;t be perfect. Protect your code and users from the
inevitable errors.

*Design with Contracts*

Use contracts to document and verify that code does no more and no less
than it claims to do.

*Crash Early*

A dead program normally does a lot less damage than a crippled one.

*Use Assertions to Prevent the Impossible*

Assertions validate your assumptions. Use them to protect your code from
an uncertain world.

*Use Exceptions for Exceptional Problems*

Exceptions can suffer from all the readability and maintainability
problems of classic spaghetti code. Reserve exceptions for exceptional
things.

*Finish What You Start*

Where possible, the routine or object that allocates a resource should
be responsible for deallocating it.

*Minimize Coupling Between Modules*

Avoid coupling by writing &quot;shy&quot; code and applying the Law of Demeter.

*Configure, Don&#39;t Integrate*

Implement technology choices for an application as configuration
options, not through integration or engineering.

*Put Abstractions in Code, Details in Metadata*

Program for the general case, and put the specifics outside the compiled
code base.

*Analyze Workflow to Improve Concurrency* Exploit concurrency in your
user&#39;s workflow.

*Design Using Services*

Design in terms of services—independent, concurrent objects behind
well-defined, consistent interfaces.

*Always Design for Concurrency*

Allow for concurrency, and you&#39;ll design cleaner interfaces with fewer
assumptions.

*Separate Views from Models*

Gain flexibility at low cost by designing your application in terms of
models and views.

*Use Blackboards to Coordinate Workflow*

Use blackboards to coordinate disparate facts and agents, while
maintaining independence and isolation among participants.

*Don&#39;t Program by Coincidence*

Rely only on reliable things. Beware of accidental complexity, and
don&#39;t confuse a happy coincidence with a purposeful plan.

*Estimate the Order of Your Algorithms*

Get a feel for how long things are likely to take before you write code.

*Test Your Estimates*

Mathematical analysis of algorithms doesn&#39;t tell you everything. Try
timing your code in its target environment.

*Refactor Early, Refactor Often*

Just as you might weed and rearrange a garden, rewrite, rework, and
re-architect code when it needs it. Fix the root of the problem.

*Design to Test*

Start thinking about testing before you write a line of code.

*Test Your Software, or Your Users Will*

Test ruthlessly. Don&#39;t make your users find bugs for you.

*Don&#39;t Use Wizard Code You Don&#39;t Understand*

Wizards can generate reams of code. Make sure you understand all of it
before you incorporate it into your project.

*Don&#39;t Gather Requirements–Dig for Them*

Requirements rarely lie on the surface. They&#39;re buried deep beneath
layers of assumptions, misconceptions, and politics.

*Workwith a User to Think Like a User*

It&#39;s the best way to gain insight into how the system will really be
used.

*Abstractions Live Longer than Details*

Invest in the abstraction, not the implementation. Abstractions can
survive the barrage of changes from different implementations and new
technologies.

*Use a Project Glossary*

Create and maintain a single source of all the specific terms and
vocabulary for a project.

*Don&#39;t Think Outside the Box–Find the Box*

When faced with an impossible problem, identify the real constraints.
Ask yourself: &quot;Does it have to be done this way? Does it have to be
done at all?&quot;

*Start When You&#39;re Ready.*

You&#39;ve been building experience all your life. Don&#39;t ignore niggling
doubts.

*Some Things Are Better Done than Described*

Don&#39;t fall into the specification spiral—at some point you need to
start coding.

*Don&#39;t Be a Slave to Formal Methods.*

Don&#39;t blindly adopt any technique without putting it into the context
of your development practices and capabilities.

*Costly Tools Don&#39;t Produce Better Designs*

Beware of vendor hype, industry dogma, and the aura of the price tag.
Judge tools on their merits.

*Organize Teams Around Functionality*

Don&#39;t separate designers from coders, testers from data modelers. Build
teams the way you build code.

*Don&#39;t Use Manual Procedures*

A shell script or batch file will execute the same instructions, in the
same order, time after time.

*Test Early. Test Often. Test Automatically*

Tests that run with every build are much more effective than test plans
that sit on a shelf.

*Coding Ain&#39;t Done &#39;Til All the Tests Run* &#39;Nuff said.

*Use Saboteurs to Test Your Testing*

Introduce bugs on purpose in a separate copy of the source to verify
that testing will catch them.

*Test State Coverage, Not Code Coverage*

Identify and test significant program states. Just testing lines of code
isn&#39;t enough.

*Find Bugs Once*

Once a human tester finds a bug, it should be the last time a human
tester finds that bug. Automatic tests should check for it from then on.

*English is Just a Programming Language*

Write documents as you would write code: honor the DRY principle, use
metadata, MVC, automatic generation, and so on.

*Build Documentation In, Don&#39;t Bolt It On*

Documentation created separately from code is less likely to be correct
and up to date.

*Gently Exceed Your Users&#39; Expectations*

Come to understand your users&#39; expectations, then deliver just that
little bit more.

*Sign Your Work*

Craftsmen of an earlier age were proud to sign their work. You should
be, too.

*Languages To Learn*

Tired of C, C++, and Java? Try CLOS, Dylan, Eiffel, Objective C, Prolog,
Smalltalk, or TOM. Each of these languages has different capabilities
and a different &quot;flavor.&quot; Try a small project at home using one or
more of them.

*The WISDOM Acrostic*

*W*hat do you want them to learn?

What *i*s their interest in what you&#39;ve got to say?

How *s*ophisticated are they?

How much *d*etail do they want?

Whom do you want to *o*wn the information?

How can you *m*otivate them to listen to you?

*How to Maintain Orthogonality*

____

Design independent, well-defined components.

Keep your code decoupled.

Avoid global data.

Refactor similar functions.

____

*Things to prototype*

____

Architecture

New functionality in an existing system

Structure or contents of external data

Third-party tools or components Performance issues

User interface design

____

*Architectural Questions*

____

Are responsibilities well defined?

Are the collaborations well defined?

Is coupling minimized?

Can you identify potential duplication?

Are interface definitions and constraints acceptable? Can modules
access needed data—when needed?

____

*Debugging Checklist*

____

Is the problem being reported a direct result of the underlying bug,
or merely a symptom?

Is the bug really in the compiler? Is it in the OS? Or is it in your
code?

If you explained this problem in detail to a coworker, what would you
say?

If the suspect code passes its unit tests, are the tests complete
enough? What happens if you run the unit test with this data? Do the
conditions that caused this bug exist anywhere else in the system?

____

*Law of Demeter for Functions*

An object&#39;s method should call only methods belonging to:

____

Itself

Any parameters passed in

Objects it creates

Component objects

____

*How to Program Deliberately*

____

Stay aware of what you&#39;re doing.

Don&#39;t code blindfolded.

Proceed from a plan.

Rely only on reliable things.

Document your assumptions.

Test assumptions as well as code.

Prioritize your effort.

Don&#39;t be a slave to history.

____

*When to Refactor*

____

You discover a violation of the DRY principle.

You find things that could be more orthogonal.

Your knowledge improves.

The requirements evolve.

You need to improve performance.

____

*Cutting the Gordian Knot*

When solving _impossible_ problems, ask yourself:

____

Is there an easier way?

Am I solving the right problem?

Why is this a problem?

What makes it hard?

Do I have to do it this way?

Does it have to be done at all?

____

*Aspects of Testing*

____

Unit testing

Integration testing

Validation and verification

Resource exhaustion, errors, and recovery

Performance testing

Usability testing

Testing the tests themselves

____